// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njejfktraxiolqbjndwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZWpma3RyYXhpb2xxYmpuZHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NTU4NzMsImV4cCI6MjA3NzUzMTg3M30.18hAN8EWMusx9Yxw40bNsjxm5bxAy1gk0APttklGwm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});